namespace Alvao.API.AM.Model;

/// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/T_Alvao_API_AM_Model_Kind.htm"/>
public static class Kind
{
    public enum DataType
    {
        KindNone = 0,
        KindText = 1,
        KindDate = 2,
        KindFloat = 3,
        KindUser = 4,
    }
    public enum KindCode
    {
        Name = 0,
        HostName = 3,
        Note = 6,
        Place = 7,
        Null = -1,
        TypeDesignation = 10,
        InventaryNo = 11,
        SerialNo = 12,
        PackingSlipNo = 13,
        Port = 14,
        Manufacturer = 16,
        Type = 17,
        Frequency = 18,
        RefreshMax = 19,
        Version = 23,
        Supplier = 38,
        PurchaseDate = 40,
        Warranty = 41,
        PcDescription = 42,
        OrganizationName = 48,
        Size = 50,
        LoginName = 54,
        VideoRam = 55,
        Centre = 57,
        MACAddress = 61,
        IPAddress = 62,
        Domain = 63,
        Interface = 68,
        UserPersonalId = 74,
        ComputerKind = 78,
        BIOS_SN = 87,
        RAMSlots = 93,
        RAMUsedSlots = 94,
        MaxSize = 95,
        Model = 96,
        WakeUpType = 97,
        ChassisType = 98,
        PartOfDomain = 99,
        Quantity = 100,
        Category = 101,
        EvidentaryNo = 102,
        ProcessorId = 104,
        LandeskId = 105,
        WarrantyUntil = 106,
        IMEI = 122,
        VmHostName = 137,
        LastLoggedUser = 139,
        NumberOfLogicalProcessors = 140,
        RAMCapacityInGB = 147,
        TotalStorageSpaceInGB = 148,
        HdQuantity = 149,
        Procesor = 150,
        ProcesorQuantity = 151,
        OperatingSystem = 152,
        MACAddresses = 153,
        IPAddresses = 154,
        GraphicCard = 155,
        NumberOfCores = 156,
        IntuneDeviceId = 166,
        UserUpn = 167,
        IntuneLastCheckIn = 168,
    }
}
