namespace Alvao.API.SD.Model;

/// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html"/>
public sealed class TemplatesVariablesConsts {
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalByEmail"/>
    public const string ApprovalByEmail = "ApprovalByEmail";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalByForm"/>
    public const string ApprovalByForm = "ApprovalByForm";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalResultWithComment"/>
    public const string ApprovalResultWithComment = "ApprovalResultWithComment";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalStepCurrentApprovers"/>
    public const string ApprovalStepCurrentApprovers = "ApprovalStepCurrentApprovers";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalStepExpirationTime"/>
    public const string ApprovalStepExpirationTime = "ApprovalStepExpirationTime";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_CommentForApprover"/>
    public const string CommentForApprover = "CommentForApprover";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_CommentForRequester"/>
    public const string CommentForRequester = "CommentForRequester";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_DeviceCode"/>
    public const string DeviceCode = "sHdTicketDeviceCode";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_FeedbackGeneralForm"/>
    public const string FeedbackGeneralForm = "FeedbackGeneralForm";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_FeedbackUrl"/>
    public const string FeedbackUrl = "FeedbackUrl";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_FirstReactionDeadline"/>
    public const string FirstReactionDeadline = "FirstReactionDeadline";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Group"/>
    public const string Group = "sHdTicketGroup";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Impact"/>
    public const string Impact = "Impact";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_LatestImportantMessage"/>
    public const string LatestImportantMessage = "LatestImportantMessage";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_MessageForRequester"/>
    public const string MessageForRequester = "MessageForRequester";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_MessageForSolver"/>
    public const string MessageForSolver = "MessageForSolver";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Objects"/>
    public const string Objects = "Objects";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_ObjectsPath"/>
    public const string ObjectsPath = "ObjectsPath";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessage"/>
    public const string OriginalMessage = "OriginalMessage";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageAttachmentList"/>
    public const string OriginalMessageAttachmentList = "OriginalMessageAttachmentList";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageAttachments"/>
    public const string OriginalMessageAttachments = "OriginalMessageAttachments";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageSubject"/>
    public const string OriginalMessageSubject = "OriginalMessageSubject";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Priority"/>
    public const string Priority = "Priority";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_RelatedAccount"/>
    public const string RelatedAccount = "RelatedAccountId";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Requester"/>
    public const string Requester = "sHdTicketUser";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_RequesterCompany"/>
    public const string RequesterCompany = "sHdTicketUserCompany";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_RequesterDepartment"/>
    public const string RequesterDepartment = "sHdTicketUserDepartment";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Sla"/>
    public const string Sla = "SLA";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketDeadline"/>
    public const string TicketDeadline = "TicketDeadline";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketID"/>
    public const string TicketID = "TicketID";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketInfo"/>
    public const string TicketInfo = "TicketInfo";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketMessageTag"/>
    public const string TicketMessageTag = "TicketMessageTag";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketMessageTagLink"/>
    public const string TicketMessageTagLink = "TicketMessageTagLink";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForAccountName"/>
    public const string TicketRequestedForAccountName = "TicketRequestedForAccountName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForDepartment"/>
    public const string TicketRequestedForDepartment = "TicketRequestedForDepartment";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForEmail"/>
    public const string TicketRequestedForEmail = "TicketRequestedForEmail";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForEmail2"/>
    public const string TicketRequestedForEmail2 = "TicketRequestedForEmail2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForManagerName"/>
    public const string TicketRequestedForManagerName = "TicketRequestedForManagerName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForMobile"/>
    public const string TicketRequestedForMobile = "TicketRequestedForMobile";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForName"/>
    public const string TicketRequestedForName = "TicketRequestedForName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForOffice"/>
    public const string TicketRequestedForOffice = "TicketRequestedForOffice";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForOtherContacts"/>
    public const string TicketRequestedForOtherContacts = "TicketRequestedForOtherContacts";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPersonalNumber"/>
    public const string TicketRequestedForPersonalNumber = "TicketRequestedForPersonalNumber";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPhoneToWork"/>
    public const string TicketRequestedForPhoneToWork = "TicketRequestedForPhoneToWork";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPhoneToWork2"/>
    public const string TicketRequestedForPhoneToWork2 = "TicketRequestedForPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPosition"/>
    public const string TicketRequestedForPosition = "TicketRequestedForPosition";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterAccountName"/>
    public const string TicketRequesterAccountName = "TicketRequesterAccountName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterDepartment"/>
    public const string TicketRequesterDepartment = "TicketRequesterDepartment";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterEmail"/>
    public const string TicketRequesterEmail = "TicketRequesterEmail";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterEmail2"/>
    public const string TicketRequesterEmail2 = "TicketRequesterEmail2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterManagerName"/>
    public const string TicketRequesterManagerName = "TicketRequesterManagerName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterMobile"/>
    public const string TicketRequesterMobile = "TicketRequesterMobile";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterName"/>
    public const string TicketRequesterName = "TicketRequesterName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterOffice"/>
    public const string TicketRequesterOffice = "TicketRequesterOffice";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterOtherContacts"/>
    public const string TicketRequesterOtherContacts = "TicketRequesterOtherContacts";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPersonalNumber"/>
    public const string TicketRequesterPersonalNumber = "TicketRequesterPersonalNumber";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPhoneToWork"/>
    public const string TicketRequesterPhoneToWork = "TicketRequesterPhoneToWork";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPhoneToWork2"/>
    public const string TicketRequesterPhoneToWork2 = "TicketRequesterPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPosition"/>
    public const string TicketRequesterPosition = "TicketRequesterPosition";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketService"/>
    public const string TicketService = "TicketService";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketServicePhone"/>
    public const string TicketServicePhone = "TicketServicePhone";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketServiceProcess"/>
    public const string TicketServiceProcess = "TicketServiceProcess";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSla"/>
    public const string TicketSla = "TicketSLA";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverAccountName"/>
    public const string TicketSolverAccountName = "TicketSolverAccountName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverDepartment"/>
    public const string TicketSolverDepartment = "TicketSolverDepartment";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverEmail"/>
    public const string TicketSolverEmail = "TicketSolverEmail";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverEmail2"/>
    public const string TicketSolverEmail2 = "TicketSolverEmail2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverManagerName"/>
    public const string TicketSolverManagerName = "TicketSolverManagerName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverMobile"/>
    public const string TicketSolverMobile = "TicketSolverMobile";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverName"/>
    public const string TicketSolverName = "TicketSolverName";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverOffice"/>
    public const string TicketSolverOffice = "TicketSolverOffice";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverOtherContacts"/>
    public const string TicketSolverOtherContacts = "TicketSolverOtherContacts";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPersonalNumber"/>
    public const string TicketSolverPersonalNumber = "TicketSolverPersonalNumber";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPhoneToWork"/>
    public const string TicketSolverPhoneToWork = "TicketSolverPhoneToWork";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPhoneToWork2"/>
    public const string TicketSolverPhoneToWork2 = "TicketSolverPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPosition"/>
    public const string TicketSolverPosition = "TicketSolverPosition";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketStatus"/>
    public const string TicketStatus = "TicketStatus";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketTitle"/>
    public const string TicketTitle = "TicketTitle";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_TicketUrl"/>
    public const string TicketUrl = "TicketUrl";
    /// <see href="https://doc.alvao.com/en/25/alvao-api/api/Alvao.API.SD.Model.TemplatesVariablesConsts.html#Alvao_API_SD_Model_TemplatesVariablesConsts_Urgency"/>
    public const string Urgency = "Urgency";
}
