namespace Alvao.API.SD.Model;

/// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/T_Alvao_API_SD_Model_TemplatesVariablesConsts.htm"/>
public sealed class TemplatesVariablesConsts {
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalByEmail.htm"/>
    public const string ApprovalByEmail = "ApprovalByEmail";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalByForm.htm"/>
    public const string ApprovalByForm = "ApprovalByForm";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalResultWithComment.htm"/>
    public const string ApprovalResultWithComment = "ApprovalResultWithComment";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalStepCurrentApprovers.htm"/>
    public const string ApprovalStepCurrentApprovers = "ApprovalStepCurrentApprovers";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_ApprovalStepExpirationTime.htm"/>
    public const string ApprovalStepExpirationTime = "ApprovalStepExpirationTime";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_CommentForApprover.htm"/>
    public const string CommentForApprover = "CommentForApprover";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_CommentForRequester.htm"/>
    public const string CommentForRequester = "CommentForRequester";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_DeviceCode.htm"/>
    public const string DeviceCode = "sHdTicketDeviceCode";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_FeedbackGeneralForm.htm"/>
    public const string FeedbackGeneralForm = "FeedbackGeneralForm";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_FeedbackUrl.htm"/>
    public const string FeedbackUrl = "FeedbackUrl";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_FirstReactionDeadline.htm"/>
    public const string FirstReactionDeadline = "FirstReactionDeadline";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Group.htm"/>
    public const string Group = "sHdTicketGroup";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Impact.htm"/>
    public const string Impact = "Impact";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_LatestImportantMessage.htm"/>
    public const string LatestImportantMessage = "LatestImportantMessage";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_MessageForRequester.htm"/>
    public const string MessageForRequester = "MessageForRequester";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_MessageForSolver.htm"/>
    public const string MessageForSolver = "MessageForSolver";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Objects.htm"/>
    public const string Objects = "Objects";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessage.htm"/>
    public const string OriginalMessage = "OriginalMessage";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageAttachmentList.htm"/>
    public const string OriginalMessageAttachmentList = "OriginalMessageAttachmentList";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageAttachments.htm"/>
    public const string OriginalMessageAttachments = "OriginalMessageAttachments";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_OriginalMessageSubject.htm"/>
    public const string OriginalMessageSubject = "OriginalMessageSubject";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Priority.htm"/>
    public const string Priority = "Priority";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_RelatedAccount.htm"/>
    public const string RelatedAccount = "RelatedAccountId";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Requester.htm"/>
    public const string Requester = "sHdTicketUser";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_RequesterCompany.htm"/>
    public const string RequesterCompany = "sHdTicketUserCompany";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_RequesterDepartment.htm"/>
    public const string RequesterDepartment = "sHdTicketUserDepartment";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Sla.htm"/>
    public const string Sla = "SLA";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketDeadline.htm"/>
    public const string TicketDeadline = "TicketDeadline";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketID.htm"/>
    public const string TicketID = "TicketID";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketInfo.htm"/>
    public const string TicketInfo = "TicketInfo";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketMessageTag.htm"/>
    public const string TicketMessageTag = "TicketMessageTag";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketMessageTagLink.htm"/>
    public const string TicketMessageTagLink = "TicketMessageTagLink";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForAccountName.htm"/>
    public const string TicketRequestedForAccountName = "TicketRequestedForAccountName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForDepartment.htm"/>
    public const string TicketRequestedForDepartment = "TicketRequestedForDepartment";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForEmail.htm"/>
    public const string TicketRequestedForEmail = "TicketRequestedForEmail";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForEmail2.htm"/>
    public const string TicketRequestedForEmail2 = "TicketRequestedForEmail2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForManagerName.htm"/>
    public const string TicketRequestedForManagerName = "TicketRequestedForManagerName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForMobile.htm"/>
    public const string TicketRequestedForMobile = "TicketRequestedForMobile";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForName.htm"/>
    public const string TicketRequestedForName = "TicketRequestedForName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForOffice.htm"/>
    public const string TicketRequestedForOffice = "TicketRequestedForOffice";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForOtherContacts.htm"/>
    public const string TicketRequestedForOtherContacts = "TicketRequestedForOtherContacts";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPersonalNumber.htm"/>
    public const string TicketRequestedForPersonalNumber = "TicketRequestedForPersonalNumber";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPhoneToWork.htm"/>
    public const string TicketRequestedForPhoneToWork = "TicketRequestedForPhoneToWork";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPhoneToWork2.htm"/>
    public const string TicketRequestedForPhoneToWork2 = "TicketRequestedForPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequestedForPosition.htm"/>
    public const string TicketRequestedForPosition = "TicketRequestedForPosition";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterAccountName.htm"/>
    public const string TicketRequesterAccountName = "TicketRequesterAccountName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterDepartment.htm"/>
    public const string TicketRequesterDepartment = "TicketRequesterDepartment";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterEmail.htm"/>
    public const string TicketRequesterEmail = "TicketRequesterEmail";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterEmail2.htm"/>
    public const string TicketRequesterEmail2 = "TicketRequesterEmail2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterManagerName.htm"/>
    public const string TicketRequesterManagerName = "TicketRequesterManagerName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterMobile.htm"/>
    public const string TicketRequesterMobile = "TicketRequesterMobile";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterName.htm"/>
    public const string TicketRequesterName = "TicketRequesterName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterOffice.htm"/>
    public const string TicketRequesterOffice = "TicketRequesterOffice";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterOtherContacts.htm"/>
    public const string TicketRequesterOtherContacts = "TicketRequesterOtherContacts";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPersonalNumber.htm"/>
    public const string TicketRequesterPersonalNumber = "TicketRequesterPersonalNumber";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPhoneToWork.htm"/>
    public const string TicketRequesterPhoneToWork = "TicketRequesterPhoneToWork";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPhoneToWork2.htm"/>
    public const string TicketRequesterPhoneToWork2 = "TicketRequesterPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketRequesterPosition.htm"/>
    public const string TicketRequesterPosition = "TicketRequesterPosition";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketService.htm"/>
    public const string TicketService = "TicketService";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketServicePhone.htm"/>
    public const string TicketServicePhone = "TicketServicePhone";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketServiceProcess.htm"/>
    public const string TicketServiceProcess = "TicketServiceProcess";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSla.htm"/>
    public const string TicketSla = "TicketSLA";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverAccountName.htm"/>
    public const string TicketSolverAccountName = "TicketSolverAccountName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverDepartment.htm"/>
    public const string TicketSolverDepartment = "TicketSolverDepartment";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverEmail.htm"/>
    public const string TicketSolverEmail = "TicketSolverEmail";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverEmail2.htm"/>
    public const string TicketSolverEmail2 = "TicketSolverEmail2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverManagerName.htm"/>
    public const string TicketSolverManagerName = "TicketSolverManagerName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverMobile.htm"/>
    public const string TicketSolverMobile = "TicketSolverMobile";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverName.htm"/>
    public const string TicketSolverName = "TicketSolverName";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverOffice.htm"/>
    public const string TicketSolverOffice = "TicketSolverOffice";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverOtherContacts.htm"/>
    public const string TicketSolverOtherContacts = "TicketSolverOtherContacts";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPersonalNumber.htm"/>
    public const string TicketSolverPersonalNumber = "TicketSolverPersonalNumber";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPhoneToWork.htm"/>
    public const string TicketSolverPhoneToWork = "TicketSolverPhoneToWork";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPhoneToWork2.htm"/>
    public const string TicketSolverPhoneToWork2 = "TicketSolverPhoneToWork2";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketSolverPosition.htm"/>
    public const string TicketSolverPosition = "TicketSolverPosition";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketStatus.htm"/>
    public const string TicketStatus = "TicketStatus";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketTitle.htm"/>
    public const string TicketTitle = "TicketTitle";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_TicketUrl.htm"/>
    public const string TicketUrl = "TicketUrl";
    /// <see href="https://doc.alvao.com/en/alvao_11_2/alvao_api/html/F_Alvao_API_SD_Model_TemplatesVariablesConsts_Urgency.htm"/>
    public const string Urgency = "Urgency";
}
